version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings
        columns:
          - name: room_type
            tests: # this test is 3rd party test from calogica/dbt_expectations installed in package.yml
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4
          - name: price
            tests: # this test is 3rd party test from calogica/dbt_expectations installed in package.yml
              - dbt_expectations.expect_column_values_to_match_regex:
                  regex: "^\\\\$[0-9][0-9\\\\.]+$"

      - name: hosts
        identifier: raw_hosts

      - name: reviews
        identifier: raw_reviews
        freshness:
          warn_after:
            count: 1
            period: hour
          error_after:
            count: 24
            period: hour
        loaded_at_field: date
